### PR TITLE
feat: mattermost integration

### PR DESCRIPTION
**Pull request by gempain**
- Adds mattermost integration (passport implementation + sign-in button)
- Make avatar conditional to avoid break the design when `avatarUrl` is empty

I tried to get around the avatar url authentication issue by converting to base64 but I was not able to save it to the database as the max length for the avatarUrl column is 255. Is there a way to save the file to AWS3 ? I'm sure outline exposes a service somewhere to do so, but haven't had the time to dig in. I'll leave this for someone else.

Keep up the great work.

### CODE REVIEW

**Comment by jakoblorz** [comment]
This is great! The plugin architecture I have in mind will also allow the developer to add the login button jsx somewhere along the boarding code, so that changes in the core server codebase are not necessary. 
Concerning the avatarUrl issue, we could make the appropriate changes along https://github.com/outline/outline/issues/1317 so that base64 encoded images can be stored in the database. But still, there has to be a cap on the image size though. 
@gempain

**Comment by gempain** [comment]
@jakoblorz got it. I think the best pattern is to store it to S3 and then store the URL in the DB. I just haven't figured out how S3 is accessed in Outline (haven't looked, TBH).

**Comment by almereyda** [comment]
This also seems to include a Discord adaptor, that is not spoken of. Is it working?

For documentation purposes that could be added to the headline, or be remarked to in the original post/merge commit description.

**Comment by gempain** [comment]
I'm closing this.

**Pull request closed without merging**
